variable "google_project" {
  description = "(Required) this field should be your personal project id. The project indicates the default GCP project all of your resources will be created in. Most Terraform resources will have a project field"
  type        = string
}

variable "google_region" {
  description = "(Required) The region will be used to choose the default location for regional resources. Regional resources are spread across several zones."
  type        = string
}

variable "google_credentials" {
  description = "(Required) Currently the only supported service account credentials are credentials downloaded from Cloud Console or generated by gcloud"
  type        = string
}

variable "cloud_sql_proxy_url" {
  description = "Download the Cloud SQL Auth proxy: Linux 64-bit - https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64, macOS 64-bit - https://dl.google.com/cloudsql/cloud_sql_proxy.darwin.amd64, Mac M1 - https://dl.google.com/cloudsql/cloud_sql_proxy.darwin.arm64"
  type        = string
  default     = "https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64"
}
